# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestSOAP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestSOAP
  pod 'Alamofire'
  pod 'SOAPEngine'
  pod 'Charts'
end
